---
# title: "Data Cleaning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
```

# Reading Data

All the values marked as '?' have been read-in as NA's using built-in feature of pandas read_csv method.  
```{python}
import pandas as pd
df_original = pd.read_csv('Blood_Pressure_data.csv', na_values='?',  )
```

## Data Summaries  

We first examine the percentage of missing values in each column as follows: 
```{python}
df = df_original
percent_missing = round(df.isnull().sum() * 100 / len(df),2)
missing_value_df = pd.DataFrame({'Variable': df.columns,
                                 'MissingPercent': percent_missing})
missing_value_df.sort_values('MissingPercent', inplace=True, ascending=False)
missing_value_df[missing_value_df.MissingPercent>0]
```
Now consider the number of unique values in each variable, specially in categorical variables:  
```{python}
df.nunique()
```

## Data Cleaning  

Combining the information present in Missing Values, Number of distinct values and Variable Types we perform certain cleaning tasks and also apply a transformation on label variable. Details of these cleaning steps are as follows:  

- Replace all "?" with NA (Not Available).  

- Factors '>5' and '<30' have been lumped together in new category named 'YES'.  
  
```{python}
# dt = pd.DataFrame({'a':[1,3,3,1], 'b':[2,2,4,5]})
label_dict = {'>5':'YES', '<30':'YES','NO':'NO'}
df = df.replace(dict(label=label_dict))
df.head(20)
```
**Variables to be Deleted:**  

- *id, weight, discharge_disposition_id, admission_source_id, patient_no and admission_typeid* are useless because of having more than 10 factors   

- *payer_code and medical_specialty* have very high number of factors 17 and 72, respectively.  Moreover they contain integer and alphanumeric factors simultaneously.  

- *examide* and *citoglipton* have only 1 factor throughout i.e. have 0 variance  

- *repaglinide, nateglinide, chlorpropamide, acetohexamide, tolbutamide, acarbose, miglitol, troglitazone, tolazamide, glyburide, glipizide, glimepiride-pioglitazone, metformin, metformin-pioglitazone, metformin-rosiglitazone, glipizide-metformin* have abnormal factor counts, which may also be visualized through graphs on the Visualization page of this website. 


```{python}
cols_to_delete = ['id', 'weight', 'discharge_disposition_id', 'admission_source_id', 'patient_no', 'admission_typeid','payer_code', 'medical_specialty', 'examide', 'citoglipton', 'repaglinide', 'nateglinide', 'chlorpropamide', 'acetohexamide', 'tolbutamide', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'glyburide', 'glipizide', 'glimepiride-pioglitazone', 'metformin', 'metformin-pioglitazone', 'metformin-rosiglitazone', 'glipizide-metformin','diag_1', 'diag_2', 'diag_3']

df = df_original.drop(cols_to_delete, axis=1, inplace=False)

df.columns

```

- Variables to be converted into categorical ones: *cast,gender,age group,max_glu_serum,A1Cresult, glimepiride, pioglitazone, rosiglitazone, insulin, glyburide-metformin, change, Med, label*  

```{python}
df['cast'] = df['cast'].astype('category')
df['gender'] = df['gender'].astype('category')
df['age group'] = df['age group'].astype('category')
df['max_glu_serum'] = df['max_glu_serum'].astype('category')
df['A1Cresult'] = df['A1Cresult'].astype('category')
df['glimepiride'] = df['glimepiride'].astype('category')
df['pioglitazone'] = df['pioglitazone'].astype('category')
df['rosiglitazone'] = df['rosiglitazone'].astype('category')
df['insulin'] = df['insulin'].astype('category')
df['glyburide-metformin'] = df['glyburide-metformin'].astype('category')
df['change'] = df['change'].astype('category')
df['Med'] = df['Med'].astype('category')
df['label'] = df['label'].astype('category')
# df.to_csv('data_pandas_cleaned.csv')
print(df.info())
```