---
title: "Task Statement"
author: "Mahreen Athar"
date: "12/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Assignment  

You have to perform a classification on provided dataset of Heart Attack prediction.
For that prediction, first of all you have to preprocess dataset and convert it into
appropriate numeric form. Then you have to perform any Machine Learning model for the
prediction of Label. Here are some outcomes of the project that I expect from that I expect
from you.  
  
1. Preprocessing  
  
2. Applying more than 3 Machine Learning algorithms for the prediction and apply
majority voting concept for the final output. Majority voting means to take Predicted labels
from all applied classifiers and assign final label according to majority vote.  
  
3. Exploratory Data Analysis: Lot of graphs to understand the Data insights.  
  
4. Accuracy, F Score more than 65 percent. The more the F-score, more marks will be
awarded.  

You can use Numpy, Pandas, Sklearn, Matplotlib library for that.  

## Warning  
In case of plagiarism you will be awarded 0 marks in Project and got F grade in Exam
too.